### ISSUE TITLE
为什么我到step1后网页是空白的

### ISSUE THREAD

**Issue by aierlma** [TheZihanGu/oneindex-tzg#1]
就是环境检测之后点击下一步就是空白的，网页也不加载了，但是step2还能正常显示

**Comment by TheZihanGu** [comment]
方便发个截图么...还有出问题的站点链接。

**Comment by aierlma** [comment]
![批注 2020-08-18 200544](https://user-images.githubusercontent.com/55280375/90511028-799a9180-e18e-11ea-8729-dc2ea2ad3d57.jpg)
![批注 2020-08-18 200648](https://user-images.githubusercontent.com/55280375/90511053-84edbd00-e18e-11ea-80cd-37594e10d36e.jpg)
就是这样的，试了不同的浏览器，不知道，啥情况，站点链接就在网页上方

**Comment by TheZihanGu** [comment]
了解了，应该是页面错误导致的...之前的Commit我没有测试🤦‍♂️
我稍后修复一下吧。

**Comment by TheZihanGu** [comment]
辛苦把 6a90b95 中对 /controller/AdminController.php 删除的内容重新添加到此文件中，然后再次访问一下 step1。

**Comment by aierlma** [comment]
感谢大佬，可以了！

**Comment by TheZihanGu** [comment]
果然是这个问题啊...
等我明天再改一下，发个新版本吧。

**Comment by TheZihanGu** [comment]
该问题已在 6b93aae 修复。
